brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
indent_style = "Visual"
match_block_trailing_comma = true
combine_control_expr = false
where_single_line = true
newline_style = "Unix"
hard_tabs = true
max_width = 120
use_small_heuristics = "Max"
